# Generated by Django 4.2 on 2023-07-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='state',
        ),
    ]
